### ISSUE TITLE
crocoa

### ISSUE THREAD

**Issue by segecey** [manastech/crocoa#1]
crocoa will continue to be developed ?

**Comment by bcardiff** [comment]
We want. We are bit more focused on crystal language and tools.

The last status was experimenting with
1. a better type hierarchy to be comfortable to the user and the compiler.
2. automatic generation of obj-c methods from headers.

There is no clear roadmap.
If you have certain needs or input we can discuss them.
If you want to contribute we can sync and try to move this forward.

**Comment by sfcgeorge** [comment]
FWIW I love the idea of being able to write OS X native GUIs in something simpler than Objective-C. I realise you can already do it with MacRuby / RubyMotion but I think Crystal would be a better fit—probably faster and the macros would surely come in handy. Writing a nice DSL to make Cocoa GUIs much simpler would be very cool. Alas I don't actually know Obj-C / Cocoa so I can't help, I just wanted to say good work so far :+1:

**Comment by solisoft** [comment]
Hi there, 

When I try to run a minimalist.cr sample I have :
Error in ./app.cr:1: while requiring "crocoa"

require "crocoa"
^

in ./libs/crocoa/crocoa.cr:1: while requiring "./objc/*"

require "./objc/*"
^

Syntax error in ./libs/crocoa/objc/lib_objc.cr:45: octal constants should be prefixed with 0o

```
RETAIN  = 01401u64,
```

any idea?

**Comment by bcardiff** [comment]
@solisoft for the time being crocoa is a bit outdated, sorry. 

Some breaking changes in crystal requires some updates in the source. The one you point is about octal numbers, but when I tried to fix them more, regarding macro semantic appears. It seems last working crystal for crocoa is around 0.5.3 , pretty old.

I hope we will find time to bring this up and running again. Right now, we are more working in language and tools.
